<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Using an older SDK? Change this to net8.0 or net9.0. Nothing else needs to change. -->
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Seed\products.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
